[tools]
erlang = "28.3.1"
elixir = "1.19.5-otp-28"
node = "24.14.0"
go = ["1.26.0", "1.23.6"]
golangci-lint = "2.10.1"
bun = "1.3.12"
# Aqua
"aqua:opencode" = "1.1.63"
"aqua:cli/cli" = "2.89.0"
# NPM
npm = "11.12.1"
"npm:repomix" = "1.13.1"
"npm:@devcontainers/cli" = "0.85.0"
"npm:@mariozechner/pi-coding-agent" = "0.68.1"
"aqua:pnpm" = "10.30.1"

[settings]
experimental = true
