# Enable mouse support
set -g mouse on

# Start windows and panes numbering at 1
set -g base-index 1
set -g pane-base-index 1

# Status bar left and right content
set -g status-position top
set -g status-style bg=#3E7FB5,fg=white
set -g status-left " "
set -g status-right-length 100
set -g status-right "[#(echo #{pane_current_path} | rev | cut -d/ -f-2 | rev)] · #(LC_TIME=C date +'%a, %b%e %I:%M %p') · #(bash ~/.config/tmux/scripts/battery.sh) "
set -g status-interval 5

# Status bar window indicators
set -g window-status-format "#[fg=white] #I:#W "
set -g window-status-current-format "#[fg=black,bg=white] #I:#W "

# Scrollback history limit and disable automatic renaming
set -g history-limit 3000
set -g allow-rename off

# Preserve terminal environment variables
set -g allow-passthrough on

# Update environment variables
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
# Add theme-related environment variables
set -ga update-environment APPEARANCE
set -ga update-environment THEME
set -ga update-environment COLORSCHEME

# Key bindings for pane and window management
bind | split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4

# Enable multi-line mouse selection
bind -n MouseDrag1Pane if -F '#{pane_in_mode}' 'send-keys -X begin-selection' 'copy-mode -M'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind -T copy-mode    MouseDragEnd1Pane send-keys -X copy-selection-and-cance

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-save-dir '~/.local/share/tmux/resurrect'

set -g @continuum-boot 'off'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '3'

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

run '~/.config/tmux/plugins/tpm/tpm'


